#!/bin/bash
echo prepare-commit-message - i am alive !!!
cat .git/COMMIT_EDITMSG | { read issue mytext;
	if [ $issue == ${issue//[^0-9]/} -a "$issue" != "" ]; then
	    if [ -e ~/.jirarc ]; then
		. ~/.jirarc
	    fi
	    if [ "X${JIRA_USER}" == "X" -o "X${JIRA_PASSWORD}" == "X" ]; then
		echo "JIRA credentials not defined "
		exit 1
	    fi
	    tmpFile=$( mktemp /tmp/jiraXXXX )
	    EXIT_CODE=$( curl --silent -u ${JIRA_USER}:${JIRA_PASSWORD} --write-out '%{http_code}' -X GET --output ${tmpFile} https://innovidwiki.jira.com/rest/api/2/issue/KAN-${issue}\?fields=summary )
	    if [ ${EXIT_CODE} == 200 ]; then
		CASE_SUMM=$(sed 's/.*"summary":"\(.*\)"}.*/\1/' < ${tmpFile} | tr -d "\r\n"|sed -e 's/^ *//g' -e 's/ *$//g' )
		echo KAN-$issue "(" $CASE_SUMM ")" "[" $mytext "]"   > $1
		cat $1 | grep -q "Could not find issue with key"
		if [[ $? -eq 0 ]]; then
		    echo "case does not exist in Jira "
		    exit 1
		fi
	    else
		echo "Given KanBan ticket number doesn't exist"
		exit 3
	    fi
	else
		echo "No KanBan ticket number given"
		exit 1
	fi
	if [ -z "$CASE_SUMM" ] ; then
		echo "No such KanBan ticket found: #${issue}"
		exit 2
	fi
}
