#!/bin/sh
BASE_DIR=`dirname "$0"`
if [ "`uname`" = "Linux" ]; then
    BASE_DIR=`readlink -m "${BASE_DIR}"`
fi

OUTFILE=git-clone-out.$$
if git clone "$@" --progress 2>&1 | tee ${OUTFILE} ; then
    DIR=`grep '^Cloning into ' "${OUTFILE}" | sed -e "s#^Cloning into '\(.*\)'\.\.\..*#\1#"`
    rm ${DIR}/.git/hooks/*.sample
    for HOOK in ${BASE_DIR}/git-hooks/* ; do
        ln -s "${HOOK}" "${DIR}/.git/hooks/"
        if [ $? != 0 ]; then
            cp "${HOOK}" "${DIR}/.git/hooks/"
        fi
    done
fi
rm "${OUTFILE}"

