#!/bin/bash

repo=$(basename `git rev-parse --show-toplevel`)
get_issues=`git log @{u}..  --pretty=oneline --abbrev-commit | awk '{ print $2 }'`
jira_issues=`echo ${get_issues} | tr " " ,`
num_of_commits=`git log @{u}.. | grep commit | wc -l | tr -d '[[:space:]]'`
patch_file_path='/tmp/patch_pre_push_commits.txt'
git format-patch -${num_of_commits} --stdout > ${patch_file_path}

command -v crucibot > /dev/null &&  crucibot --jira-issues ${jira_issues} --patch ${patch_file_path} --repo ${repo} || echo "You don't have crucibot installed on your system."